import Head from 'next/head'

import { Inter } from '@next/font/google'
import Link from "next/link"
import Projects from "./Project/Project"
import Experience from './Experience/Experience'
const inter = Inter({ subsets: ['latin'] })

export default function Home({data,data_again}) {


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
       {console.log(data_again)}
       <div style={{display:"flex",justifyContent:"flex-start",border:"red"}}>
       <div style={{display:"flex",justifyContent:"center",alignItems:"center",flexDirection:"column",width:"30%" }}>
       <img
       src="https://avatars.githubusercontent.com/u/40817224?v=4"
       width="50px"
      
     />
    
     <Link href="https://api.github.com/users/vermabraj/repos"> <h1>{data.name}</h1></Link>
     <p>{data.login}</p>
     <div style={{display:"flex",justifyContent:"space-between"}}>
     <span><b>Followers:</b>{data.followers} | <b>Following:</b>{data.following}</span></div>
     <div style={{display:"flex",justifyContent:"space-between"}}>
   <button style={{background:"blue",borderRadius:"10px",padding:"10px"}} onClick={()=>window.open("https://drive.google.com/file/d/1iRX3957aRE2asiMleyLksndLZOFJUkM0/view?usp=sharing")}>Resume</button>{" "}{" "}
   <button  style={{background:"green",borderRadius:"10px",padding:"10px"}} onClick={()=>window.open("https://github.com/vermabraj")}>Follow</button>
     </div>
     <h3 style={{marginLeft:"20px",marginTop:"30px"}}>Full-stack Developer | FOSS | JavaScript | Typescript | NodeJS | Deno | ReactJS | HTML | CSS | Chakra-UI | MUI</h3>
     <div style={{display:"flex",justifyContent:"space-between",flexDirection:"column"}}>
    
    
     <div style={{display:"flex",justifyContent:"space-between",marginTop:"30px"}}><button style={{padding:"10px",borderRadius:"30px",marginRight:"10px"}}>1</button>
     <div>
     <h2>SDE-3 at{" "}{data.company}</h2>
     <p>14 - june-2021 - Present</p>
     </div>
     </div>
     </div>
     </div>
       
      
       <div style={{display:"flex",flexDirection:"column"}}>
       <div>
<h2>{data_again.items[0].full_name}</h2>
<p>{data_again.items[0].name}</p>
       </div>
       
       <div>
<h2>{data_again.items[1].full_name}</h2>
<p>{data_again.items[1].name}</p>
       </div>
       
       <div>
<h2>{data_again.items[2].full_name}</h2>
<p>{data_again.items[2].name}</p>
       </div>
       
       <div>
<h2>{data_again.items[3].full_name}</h2>
<p>{data_again.items[3].name}</p>
       </div>

       </div>
       </div>
      </main>
      
    </>
  )
}


export async function getServerSideProps(){
  let res = await fetch(`https://api.github.com/users/vermabraj`)
  let  resAgain = await fetch(`https://api.github.com/search/repositories?q=user:vermabraj+fork:true&sort=updated&per_page=10&type=Repositories`);

  let data = await res.json()
  let data_again = await resAgain.json()
  return {
      props:{
          data,
          data_again
      }
  }
}
